platform: x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: Visual Studio 15 2017 Win64
      QTDIR: C:\Qt\5.11\msvc2017_64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: Visual Studio 14 2015 Win64
      QTDIR: C:\Qt\5.11\msvc2015_64

build:
  parallel: true

build_script:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" .. "-DCMAKE_PREFIX_PATH=%QTDIR%"
  - cmake --build .
