sudo: required
dist: bionic
language: cpp
cache: apt
compiler:
  - gcc
  - clang
env:
  - CONFIG=minimal
  - CONFIG=full
  - CONFIG=full-debug
install:
  - tests/travis/install-build-depends
matrix:
  exclude:
    - os: osx
      compiler: gcc
os:
  - linux
  - osx
script:
  - tests/travis/build-and-test
after_success:
  - |
    if [ "$CONFIG" = "full-debug" ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
