#!/bin/sh
set -e

sudo apt-get update -qq
sudo apt-get install -qq qtbase5-dev cmake

case "$CONFIG" in
full*)
    sudo apt-get install -qq  doxygen libopus-dev libspeex-dev libtheora-dev libvpx-dev
    ;;
esac
