#!/bin/sh
set -e

if [ "$(uname -s)" = "Darwin" ]; then
    brew update
    brew unlink python@2

    case "$CONFIG" in
    full*)
        brew install doxygen gstreamer gst-plugins-base gst-plugins-good gst-plugins-ugly
        ;;
    esac
else
    sudo apt-get update -qq
    sudo apt-get install -qq clang cmake

    case "$CONFIG" in
    full*)
        sudo apt-get install -qq  doxygen graphviz libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly
        ;;
    esac
fi
