# SPDX-FileCopyrightText: 2020 Linus Jahn <lnj@kaidan.im>
#
# SPDX-License-Identifier: CC0-1.0

---
name: push-docs

on:
  push:
    branches:
      - master

jobs:
  push-doc:
    runs-on: ubuntu-latest
    env:
      PUSH_KEY_REPO_DOC_QXMPP_ORG: ${{ secrets.PUSH_KEY_REPO_DOC_QXMPP_ORG }}
      CONFIG: full
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
      - name: Install extra packages
        run: tests/travis/install-build-depends-debian
      - name: Update XEP metadata
        run: doc/doap-rendering/update-xeplist.sh
      - name: Build documentation
        run: tests/travis/push-documentation
